/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.13.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.n52.project.enforce.cs5.api;

import org.n52.project.enforce.cs5.model.Cs5DataRequest;
import org.n52.project.enforce.cs5.model.Error;
import org.n52.project.enforce.cs5.model.FeatureCollection;
import java.util.Map;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-08T13:43:38.513185600+01:00[Europe/Berlin]", comments = "Generator version: 7.13.0")
@Validated
@Tag(name = "cs5", description = "the cs5 API")
public interface Cs5Api {

    /**
     * POST /cs5_catchment_data : Add CS 5 data
     * Add CS 5 data
     *
     * @param requestBody feature data (required)
     * @return Created (status code 201)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Invalid input (status code 405)
     */
    @Operation(
        operationId = "addCs5DataAsBody",
        summary = "Add CS 5 data",
        description = "Add CS 5 data",
        tags = { "cs5" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created"),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "405", description = "Invalid input", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/cs5_catchment_data",
        produces = { "application/json" },
        consumes = { "application/enforce-cs5-data" }
    )
    
    ResponseEntity<Void> addCs5DataAsBody(
        @Parameter(name = "request_body", description = "feature data", required = true) @Valid @RequestBody Map<String, Cs5DataRequest> requestBody
    );


    /**
     * GET /cs5_catchment_data : get data gathered by CS 5
     * get data gathered by CS 5
     *
     * @return OK (status code 200)
     *         or Invalid status value (status code 400)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     */
    @Operation(
        operationId = "getCs5Data",
        summary = "get data gathered by CS 5",
        description = "get data gathered by CS 5",
        tags = { "cs5" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/vnd.geo+json", schema = @Schema(implementation = FeatureCollection.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = FeatureCollection.class))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid status value", content = {
                @Content(mediaType = "application/vnd.geo+json", schema = @Schema(implementation = Error.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid", content = {
                @Content(mediaType = "application/vnd.geo+json", schema = @Schema(implementation = Error.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "403", description = "Forbidden", content = {
                @Content(mediaType = "application/vnd.geo+json", schema = @Schema(implementation = Error.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/vnd.geo+json", schema = @Schema(implementation = Error.class)),
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/cs5_catchment_data",
        produces = { "application/vnd.geo+json", "application/json" }
    )
    
    ResponseEntity<?> getCs5Data(
        
    );

}
